/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.*;
import java.util.ArrayList;
import org.example.DialInstruction.Rotation;

public class App {
    public static void main(String[] args) {
        ArrayList<DialInstruction> instructions = new ArrayList<>();
        for (String line : readInput()) {
            Rotation rotation = line.charAt(0) == 'L' ? Rotation.LEFT : Rotation.RIGHT;
            int distance = Integer.parseInt(line.substring(1));
            DialInstruction instruction = new DialInstruction(rotation, distance);
            instructions.add(instruction);
        }

        int initialRotation = 50;
        System.out.println("The dial starts by pointing at " + initialRotation + ".");
        int currentRotation = initialRotation;
        int zeroCount = 0;
        for (DialInstruction instruction : instructions) {
            if (instruction.rotation == Rotation.LEFT) {
                int current = currentRotation % 100;
                if (current == 0) {
                    current = 100;
                }
                if (current <= instruction.distance) {
                    // Assume current = 50
                    // L500 -> passes 0 five times: at 100, 200, 300, 400, 500
                    zeroCount += 1 + (instruction.distance - current) / 100;
                }
                currentRotation = (int) (((currentRotation - instruction.distance) % 100 + 100) % 100);
            } else {
                int current = (100 - currentRotation) % 100;
                if (current == 0) {
                    current = 100;
                }
                if (current <= instruction.distance) {
                    zeroCount += 1 + (instruction.distance - current) / 100;
                }
                currentRotation = (int) ((currentRotation + instruction.distance) % 100);
            }
            System.out.println("The dial is rotated " + instruction + " to point at " + currentRotation + ".");
        }
        System.out.println("The dial points at 0 a total of " + zeroCount + " times.");
    }

    static ArrayList<String> readInput() {
        ArrayList<String> lines = new ArrayList<>();
        BufferedReader bufferedReader = null;
        try {
            FileReader fileReader = new FileReader(
                    "/Users/magroc/GitHub/advent-of-code/2025/A01/app/src/main/resources/input.txt");
            bufferedReader = new BufferedReader(fileReader);

            String line = bufferedReader.readLine();
            while (line != null) {
                lines.add(line);
                line = bufferedReader.readLine();
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (bufferedReader != null) {
                try {
                    bufferedReader.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
        return lines;
    }
}
